name: flutter_antonx_boilerplate
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  carousel_slider: ^4.0.0-nullsafety.0
  connectivity_plus: ^2.2.0
  device_info: ^2.0.2
  device_preview: ^1.1.0
  dio: ^4.0.0
  file_picker: ^4.4.0
  firebase_core: ^1.12.0
  # firebase_messaging: ^11.2.7
  firebase_crashlytics: ^2.5.2
  firebase_performance: ^0.8.0+6
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.2.2
  flutter_rating_bar: ^4.0.0
  flutter_screenutil: ^5.0.0
  flutter_staggered_grid_view: ^0.6.1
  flutter_svg: ^1.0.3
  geocoding: ^2.0.0
  geolocator: ^8.0.5
  get: ^4.1.4
  get_it: ^7.1.3
  google_maps_flutter: ^2.1.5
  heic_to_jpg: ^0.2.0
  image_picker: ^0.8.0+1
  intl: ^0.17.0
  logger: ^1.0.0
  modal_progress_hud_nsn: ^0.2.1
  permission_handler: ^9.0.2
  provider: ^6.0.3
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  rename: ^2.0.1
  
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
